/**
 * Public Images Plugin
 *
 * Generates TypeScript types for images in the /public folder, providing
 * type-safe autocomplete for the Next.js Image component's src prop.
 *
 * How it works:
 * 1. Scans /public recursively for image files
 * 2. Generates a .d.ts file with a union type of all image paths
 * 3. Augments next/image module to override the src prop type
 *
 * Output:
 * Types are generated at .next/types/public-images.d.ts alongside
 * Next.js's generated types. Ensure your tsconfig.json includes
 * .next/types in the include array.
 *
 * Supported formats:
 * jpg, jpeg, png, gif, webp, avif, svg, ico, bmp, tiff
 *
 * Valid src values:
 * - Public image paths: "/images/logo.png"
 * - External URLs: "https://example.com/image.png"
 * - Static imports: import logo from "./logo.png"
 * - Object with dimensions: { src, width, height }
 *
 * Integration:
 * Import this plugin in next.config.ts to run on every dev/build:
 * import "./plugins/next/public-images";
 */

import fs from "node:fs";
import path from "node:path";

/** Supported image file extensions */
const IMAGE_EXTENSIONS = new Set([".jpg", ".jpeg", ".png", ".gif", ".webp", ".avif", ".svg", ".ico", ".bmp", ".tiff"]);

/**
 * Recursively scans a directory for image files.
 * @param dir - Absolute path to the directory to scan
 * @param basePath - Relative path prefix for nested directories
 * @returns Array of absolute paths (e.g., "/images/logo.png")
 */
function scanPublicImages(dir: string, basePath = ""): string[] {
  const images: string[] = [];

  if (!fs.existsSync(dir)) {
    return images;
  }

  const entries = fs.readdirSync(dir, { withFileTypes: true });

  for (const entry of entries) {
    const relativePath = basePath ? `${basePath}/${entry.name}` : entry.name;

    if (entry.isDirectory()) {
      images.push(...scanPublicImages(path.join(dir, entry.name), relativePath));
    } else if (IMAGE_EXTENSIONS.has(path.extname(entry.name).toLowerCase())) {
      images.push(`/${relativePath}`);
    }
  }

  return images;
}

/**
 * Generates the TypeScript declaration file content.
 * @param images - Array of public image paths
 * @returns Complete `.d.ts` file content as a string
 */
function generateTypeDefinition(images: string[]): string {
  if (images.length === 0) {
    return `// Auto-generated by public-images plugin
// No images found in /public folder

declare module "next/image" {
  import type { ImageProps as OriginalImageProps } from "next/dist/shared/lib/image-external";

  export type PublicImagePath = never;

  export interface ImageProps extends Omit<OriginalImageProps, "src"> {
    src: OriginalImageProps["src"];
  }

  declare const Image: import("react").FC<ImageProps>;
  export default Image;
  export * from "next/dist/shared/lib/image-external";
}
`;
  }

  const unionType = images.map((img) => `"${img}"`).join("\n    | ");

  return `// Auto-generated by public-images plugin
// Run \`pnpm dev\` or \`pnpm build\` to regenerate

declare module "next/image" {
  import type { ImageProps as OriginalImageProps } from "next/dist/shared/lib/image-external";
  import type { StaticImageData } from "next/dist/shared/lib/get-img-props";

  export type PublicImagePath =
    | ${unionType};

  type ExternalUrl =
    | \`http://\${string}\`
    | \`https://\${string}\`
    | \`//\${string}\`;

  type ImageSrc =
    | PublicImagePath
    | ExternalUrl
    | StaticImageData
    | { src: string; height: number; width: number };

  export interface ImageProps extends Omit<OriginalImageProps, "src"> {
    src: ImageSrc;
  }

  declare const Image: import("react").FC<ImageProps>;
  export default Image;
  export * from "next/dist/shared/lib/image-external";
}
`;
}

/**
 * Generates TypeScript types for all images in the /public folder.
 * Only writes to disk if the content has changed.
 * @param projectRoot - Absolute path to the project root directory
 */
export function generatePublicImageTypes(projectRoot: string): void {
  const publicDir = path.join(projectRoot, "public");
  const outputPath = path.join(projectRoot, ".next", "types", "public-images.d.ts");

  const images = scanPublicImages(publicDir);
  const typeDefinition = generateTypeDefinition(images);

  const outputDir = path.dirname(outputPath);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  const existingContent = fs.existsSync(outputPath) ? fs.readFileSync(outputPath, "utf-8") : "";

  if (existingContent !== typeDefinition) {
    fs.writeFileSync(outputPath, typeDefinition);
    console.log(`[public-images] Generated types for ${images.length} image(s)`);
  }
}

// Run immediately when imported from next.config.ts
generatePublicImageTypes(process.cwd());
