/**
 * Page Routes Plugin
 *
 * Generates TypeScript type assertions that enforce each page file's
 * default export has a `path` matching its file location.
 *
 * How it works:
 * 1. Scans src/app for page.tsx files
 * 2. Converts file paths to route paths (e.g., src/app/blog/page.tsx → /blog)
 * 3. Generates a .ts file with type assertions that validate paths
 * 4. TypeScript errors if the PageFn's branded path doesn't match the expected route
 *
 * Output:
 * Types are generated at .next/types/page-routes.ts alongside
 * Next.js's generated types. Ensure your tsconfig.json includes
 * .next/types in the include array.
 *
 * Integration:
 * Import this plugin in next.config.ts to run on every dev/build:
 * import "./config/plugins/page-routes";
 */

import fs from "node:fs";
import path from "node:path";

/** Regex to strip .tsx extension from file paths */
const TSX_EXTENSION_REGEX = /\.tsx$/;

/**
 * Recursively scans a directory for page.tsx files.
 * @param dir - Absolute path to the directory to scan
 * @param basePath - Relative path prefix for nested directories
 * @returns Array of objects with filePath and routePath
 */
function scanPageFiles(dir: string, basePath = ""): Array<{ filePath: string; routePath: string }> {
  const pages: Array<{ filePath: string; routePath: string }> = [];

  if (!fs.existsSync(dir)) {
    return pages;
  }

  const entries = fs.readdirSync(dir, { withFileTypes: true });

  for (const entry of entries) {
    const relativePath = basePath ? `${basePath}/${entry.name}` : entry.name;
    const fullPath = path.join(dir, entry.name);

    if (entry.isDirectory()) {
      // Skip private folders (starting with _) and special Next.js folders
      if (!entry.name.startsWith("_") && entry.name !== "api") {
        pages.push(...scanPageFiles(fullPath, relativePath));
      }
    } else if (entry.name === "page.tsx") {
      // Convert folder path to route path
      // e.g., "blog" → "/blog", "[subdomain]" → "/[subdomain]", "" → "/"
      const routePath = basePath === "" ? "/" : `/${basePath}`;
      pages.push({ filePath: relativePath, routePath });
    }
  }

  return pages;
}

/**
 * Generates the TypeScript file content.
 * @param pages - Array of page info objects
 * @returns Complete `.ts` file content as a string
 */
function generateTypeDefinition(pages: Array<{ filePath: string; routePath: string }>): string {
  if (pages.length === 0) {
    return `// Auto-generated by page-routes plugin
// No page files found in src/app

export {};
`;
  }

  const imports = pages
    .map(({ filePath }, index) => {
      const modulePath = `~/app/${filePath.replace(TSX_EXTENSION_REGEX, "")}`;
      return `import type _Page${index} from "${modulePath}";`;
    })
    .join("\n");

  const validations = pages
    .map(({ filePath, routePath }, index) => {
      const fileLocation = `src/app/${filePath}`;
      return `
// ❌ ${fileLocation}
type _Check${index} = AssertPathMatches<typeof _Page${index}, "${routePath}", "${fileLocation}">;`;
    })
    .join("\n");

  return `// Auto-generated by page-routes plugin
// Run \`pnpm dev\` or \`pnpm build\` to regenerate
//
// This file validates that each page's Page.create path matches its file location.
// Errors will show the file path that has the mismatch.

import type { AnyPage, ExtractPagePath } from "~/platform/server/safe-page";

type AssertPathMatches<
  P extends AnyPage,
  ExpectedPath extends string,
  FileLocation extends string
> = ExtractPagePath<P> extends ExpectedPath
  ? true
  : ["❌ PATH MISMATCH in", FileLocation, "Expected:", ExpectedPath, "Got:", ExtractPagePath<P>];

// Force TypeScript to evaluate and error on mismatches
type Assert<T extends true> = T;

${imports}
${validations}

// These will error if any page has wrong path - look for the file path in the error
${pages.map((_, index) => `export type _Assert${index} = Assert<_Check${index}>;`).join("\n")}
`;
}

/**
 * Generates TypeScript types for all page files in src/app.
 * Only writes to disk if the content has changed.
 * @param projectRoot - Absolute path to the project root directory
 */
export function generatePageRouteTypes(projectRoot: string): void {
  const appDir = path.join(projectRoot, "src", "app");
  const outputPath = path.join(projectRoot, "src", "app", "__generated__", "page-routes.ts");

  const pages = scanPageFiles(appDir);
  const typeDefinition = generateTypeDefinition(pages);

  const outputDir = path.dirname(outputPath);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  const existingContent = fs.existsSync(outputPath) ? fs.readFileSync(outputPath, "utf-8") : "";

  if (existingContent !== typeDefinition) {
    fs.writeFileSync(outputPath, typeDefinition);
    console.log(`[page-routes] Generated type constraints for ${pages.length} page(s)`);
  }
}

// Run immediately when imported from next.config.ts
generatePageRouteTypes(process.cwd());
