name: 🔍 Checks

on:
  pull_request:
    branches: ['*']
  push:
    branches: ['trunk']
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

env:
  FORCE_COLOR: 3

jobs:
  setup:
    name: 🏗️ Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup CI
        uses: ./config/github/setup
        id: setup

  lint:
    name: 🧹 Lint
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup CI
        uses: ./config/github/setup
      - name: Lint
        run: pnpm lint

  typecheck:
    name: 🔬 Typecheck
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup CI
        uses: ./config/github/setup
        with:
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          vercel_org_id: ${{ vars.VERCEL_ORG_ID }}
          vercel_project_id: ${{ vars.VERCEL_PROJECT_ID }}
      - name: Build (for generating types)
        run: pnpm build
      - name: Typecheck
        run: pnpm typecheck
